d01:
	+$(MAKE) -C $@
.PHONY: d01
d02:
	+$(MAKE) -C $@
.PHONY: d02
d03:
	+$(MAKE) -C $@
.PHONY: d03

d04:
	+$(MAKE) -C $@
.PHONY: d04
d05:
	+$(MAKE) -C $@
.PHONY: d05
d06:
	+$(MAKE) -C $@
.PHONY: d06
d07:
	+$(MAKE) -C $@
.PHONY: d07
d08:
	+$(MAKE) -C $@
.PHONY: d08
d09:
	+$(MAKE) -C $@
.PHONY: d09